name: besafe
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  about: ^2.1.3
  activity_recognition_flutter: ^5.0.0
  animated_text_kit: ^4.2.2
  animated_toggle_switch: ^0.7.0
  animations: ^2.0.7
  app_links: ^3.4.3
  app_settings: ^5.0.0
  avatar_glow: ^2.0.2
  awesome_notifications: ">=0.7.4+1 <1.0.0"
  babstrap_settings_screen: ^0.1.6
  background_sms: ^0.0.4
  battery_plus: ^4.0.2
  camerawesome: ^2.0.0-dev.1
  carousel_slider: ^4.2.1
  chatview: ^1.3.1
  circular_menu: ^2.0.1
  connectivity_plus: ^4.0.2
  contacts_service: ^0.6.3
  convex_bottom_bar: ^3.2.0
  cool_alert: ^2.0.1
  device_info_plus: ^9.0.3
  dropdown_button2: ^2.3.8
  fast_contacts: ^3.0.3
  file_picker: ^5.3.4
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_activity_recognition: ^2.0.0
  flutter_animate: ^4.2.0+1
  flutter_background_service: ^5.0.1
  flutter_chat_ui: ^1.6.9
  flutter_compass: ^0.7.0
  flutter_donation_buttons: ^0.3.7
  flutter_easyloading: ^3.0.5
  flutter_map: ^5.0.0
  flutter_map_animations: ^0.4.1
  flutter_map_location_marker: ^7.0.4
  flutter_map_marker_popup: ^5.2.0
  flutter_map_supercluster: ^4.3.0
  flutter_map_tappable_polyline: ^5.0.0
  flutter_markdown: ^0.6.17+1
  flutter_phone_direct_caller: ^2.1.1
  flutter_ringtone_player: ^3.2.0
  flutter_screen_lock: ^9.0.1
  flutter_secure_storage: ^8.0.0
  flutter_share: ^2.0.0
  flutter_shortcuts: ^1.3.0
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_whatsnew: ^1.0.5+2
  fluttertoast: ^8.2.2
  font_awesome_flutter:
    git:
      url: https://github.com/fluttercommunity/font_awesome_flutter.git
      ref: bef4f3f829117241202486f8a0d836e89d167376
  geocode: ^1.0.3
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^5.0.0-release-candidate-4
  get_cli: ">=1.8.1 <2.0.0"
  get_storage: ^2.1.1
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  lat_lon_grid_plugin: ^0.2.7
  latlong2: ^0.9.0
  liquid_swipe: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  local_auth: ^2.1.6
  location_picker_flutter_map: ^1.2.2
  lottie: ^2.6.0
  map_location_picker: ^1.2.6
  material_floating_search_bar_2: ^0.5.0
  motion_toast: ^2.7.8
  network_info_plus: ^4.0.2
  onesignal_flutter: ^5.0.0
  open_filex: ^4.3.2
  open_settings: ^2.0.2
  package_info_plus: ^4.1.0
  page_transition: ^2.0.9
  path: ^1.8.3
  path_provider: ^2.1.0
  pedometer: ^4.0.1
  permission_handler: ^10.4.3
  phone_state: ^1.0.3
  quick_actions: ^1.0.5
  roam_flutter: ^0.1.5
  sensors_plus: ^3.0.3
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  showcaseview: ^2.0.3
  sidebarx: ^0.16.1
  simple_animations: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^1.10.14
  telephony: ^0.2.0
  timeago: ^3.5.0
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  vector_map_tiles: ^5.0.0
  vibration: ^1.8.1
  wakelock: ^0.6.2
  webview_flutter: ^4.2.2
  widget_circular_animator: ^1.0.0
  wiredash: ^1.7.3
  workmanager: ^0.5.1

dependency_overrides:
  win32: ^5.0.6
  dio: ^5.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: HinaMincho
      fonts:
        - asset: assets/fonts/HinaMincho-Regular.ttf
    - family: OnePiece
      fonts:
        - asset: assets/fonts/OnePiece.ttf
    - family: Yomogi
      fonts:
        - asset: assets/fonts/Yomogi-Regular.ttf
  assets:
    - assets/animations/gif/
    - assets/images/
    - assets/logo/
